### ISSUE TITLE
Allow ServerApp sub-class to override webapp handlers

### ISSUE THREAD

**Issue by vidartf** [jupyter/jupyter_server#80]
Given e.g. the case of Voilà, you want the server to not add some of the default handlers (while you want some of them). This should ideally be overridable by a subclass of `ServerApp` (but probably not user configurable?).

Taking the Voilà example again, you probably want to:
- Keep the configurable login/logout handlers.
- Keep the kernel/kernelspecs/security handlers.
- Not keep the contents/file/view/edit/nbconvert handlers.
- Modify/customize/restrict the shutdown/sessions/config handlers (?).

These are all currently [hard-coded in the web-app](https://github.com/jupyter/jupyter_server/blob/69daee7d8f8f958af3c3868adde2b7f3100a2f1c/jupyter_server/serverapp.py#L281-L297). I'm not sure what the best way to configure these would be, but the pattern from `extra_services` seems like a good one (maybe `default_services`?).

**Comment by kevin-bates** [comment]
@rolweber could add more insights but a Gateway extension will need similar functionality.

**Comment by Zsailer** [comment]
I think there's a bigger conversation to be had here. I explored an approach where the server handlers were configurable, see #31, and added it to an old draft of the Jupyter Server Enhancement proposal, and received [negative feedback](https://github.com/jupyter/enhancement-proposals/pull/28#discussion_r256226644). 

Rather than remove handlers from the core jupyter server in subclasses, I think we need to define: _What is the smallest unit that defines a jupyter server_? Then, extra handlers (like nbconvert) become server extensions.

This is open for [discussion](https://github.com/jupyter/enhancement-proposals/blob/master/jupyter-server/jupyter-server.md#clearly-define-the-smallest-unit-that-is-a-jupyter-server) in the Jupyter Server enhancement proposal (though it's received little attention). There's even an issue opened to discuss this point specifically: jupyter/enhancement-proposals#31

I would encourage us to move this conversation over there, as this has *big* implications on the Jupyter ecosystem...

**Comment by rolweber** [comment]
I think the point of the Voila example is that it needs a Jupyter Server under the covers, but does not want to appear as a Jupyter Server externally, in the network. So even if we define what constitutes a Jupyter Server, a standalone application should still have the option to use `jupyter_server` through the Python APIs, while disabling the REST APIs for the core functionality.

**Comment by vidartf** [comment]
I made [a comment on the JEP issue](https://github.com/jupyter/enhancement-proposals/issues/31#issuecomment-524262201) trying to clarify the discussion. This PR would address what I list as point 2 there.

**Comment by Zsailer** [comment]
Cool, I think this proposal makes sense then. Thanks, everyone, for clarifying (especially @vidartf for reviving conversation on the JEP). 

I think either "default_services" or "default_handlers" make sense.

**Comment by vidartf** [comment]
Closed by #84
